# This is a basic workflow to help you get started with Actions

name: Sync tieraid app

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: [sync]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone github pages of root tieraid
        uses: actions/checkout@v3
        with:
          repository: tieraid-app/tieraid-app.github.io
          ref: gh-pages
      
      - name: Setup CNAME record (for github pages to work)
        run: |
          cat << EOF > CNAME
          demo.tieraid.app
          EOF
          
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
