# This is a basic workflow to help you get started with Actions

name: Sync tieraid app

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: [sync]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    uses: tieraid-app/.github/.github/workflows/deploy-tenant.yml@main
    with:
      backend-url: https://demo.tieraid.be
